//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_demo_exam_04.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int IDsecond { get; set; }
        public int Cost { get; set; }
        public string ImageOfTable { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual SecondTable SecondTable { get; set; }
    }
}
